### ISSUE TITLE
Scan and create bookmarks

### ISSUE THREAD

**Issue by markwinger** [neural75/gqrx-scanner#14]
This is a feature request.  I would like to start a scan of the fm-broadcast band in the us, which is 88Mz to 108mhz, and make bookmarks of all the active stations it finds.  Then be be able to save he bookmarks by name/geographical location.

For example, do a scan in my home town and save it as home.  Do another scan when in Chicago and save the list as Chicago.

Now a simpler bookmark display could be displayed that show a bunch of buttons/presets for that area.   Then have the saved locations shown so can call up the bookmarks for that location.

It appears that this gqrx-scanner can already do the scanning but I see no way to have it build a bookmark list.

**Comment by neural75** [comment]
gqrx-scanner cannot modify the GUI or the bookmarks handling mechanism implemented by Gqrx. Is just a tool to control the main program externally with limited capabilities. 
The bookmark support (read-only) is already a terrible hack to overcome some limitations on the gqrx protocol and quite frankly, I don't want to fiddle too much with it because of maintainability issues that can arise in case the file format changes in the future (it is not a standard interface). 
Gqrx-scanner can process the bookmarks to perform the scan, this in general is useful to find out carriers on channels already saved from gqrx, but for now it does not save any carrier found back to the bookmark list, also because Gqrx lacks proper interface to handle multiple bookmark files. It should be possible to tag and save, but it would be painful to administer those findings from the gqrx interface (they will be all presented at the same time, not to mention that there will be no name attached to the bookmark label, could be just a timestamp from the scanner prospective). 
I prefer not to go on that route. I keep this issue open only because the output cvs report of all the carriers found  was a feature that I wanted originally, and it would make sense to adopt the same grqx bookmark format so to be (sort of) compatible on what you are asking (swapping or merging the files before starting gqrx).
But really, you should open a change request on the upstream project so that you can have multiple bookmarks per location, with a multi-tab window to select the locations perhaps. This scanner can do very little about it.

**Comment by grappas** [comment]
Wouldn't be just modifying ~/.config/gqrx/bookmarks.csv file? Obviously problem would be that you would have to restart the program to refresh newly added bookmarks but it would do the trick is it not?

**Comment by neural75** [comment]
Sorry, but I don't not want to deal with bookmarks management: this is just a command line companion tool of Gqrx. Bookmarks handling (categorization and such alike) is responsibility of the GUI. Besides, this tool is not really suitable to scan FM radio stations and a scan can produce a lot of noise and clutter the bookmarks list with many false positives (which need to be handled manually anyway). You are asking a feature that would require the upstream gqrx project to change as well to get it right. I close the issue for now, but feel free to propose a different approach to save the results.
