### ISSUE TITLE
Sweep Speed

### ISSUE THREAD

**Issue by ca** [neural75/gqrx-scanner#24]
First, I want to say that the software is excellent and it has been a lot of fun to use!
When I am experimenting with different SDR's, I am curious what is the limitation on sweep speed in the program?

Is it feasible to be able to sweep faster to take full advantage hardware that supports faster sweeps?

Thanks!

**Comment by neural75** [comment]
The limitation is the command interface with gqrx, there is a bit of delay from when you tune a freq until the signal level comes back, so if you speed up the scan too much this ping-pong reading start becoming inconsistent. There are some self-regulating algorithms to compensate for it but it cannot go faster than that. This is unrelated to the hardware support.

In order to get really fast, it would be nice to have the entire frequency spectrum data read by the sdr hardware for the tuned band, like an instant snapshot of what you see in the spectrum pane but, last time I checked, it was not possible to get this data through the gqrx command protocol.
